# Site Settings
lang: en
title: Simulation-based Inference
description: Simulation-based Inference is the next evolution in statistics
url: http://simulation-based-inference.org/
favicon: favicon.png
permalink: pretty
footer_menu: example_footer_menu

sass:
  style: compressed
  source_dir: _sass

# Custom objects
collections:
  - jobs

# Plugins settings
plugins:
  # - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

paginate: 10
paginate_path: "/papers/page:num"

disqus:
  shortname: simulation-based-inference

feed:
  disable: true

twitter:
  card: summary

markdown: kramdown

highlighter: rouge

# Defaults properties
defaults:
  - scope:
      path: ""
    values:
      hero_height: is-small
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      show_sidebar: false
  - scope:
      path: ""
      type: "jobs"
    values:
      layout: job
      hero_title: Jobs
      comments: false
      show_sidebar: false
      category: 
        - jobs

include:
  - _pages
  - _papers
  - _jobs

exclude:
  - .git/
  - __pycache__/
  - .devcontainer/
  - .github/
  - .sass-cache/
  - .vscode/
  - backend/
  - node_modules/
  - notebooks/
  - scripts/
  - .dockerignore
  - .env
  - .gitignore
  - .pre-commit-config.yaml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - main.py
  - README.md
  - tmp.ipynb
  - working.ipynb
  